Repository Dataflux-U-nidos/Backend, pull requests merged in 2025-04, with the labels that each got.

#56 ✨:(86a7d5kgh): creation of admin login test
  bun.lock
  package.json
  src/infrastructure/config/config.ts
  src/server.ts
  src/tests/integration/index.ts
  src/tests/integration/logIn/logInAdministrator.test.ts
Labels: enhancement

#57 ✨♻️ Feature Login and Registry and Refactor (86a7dug8y), (86a7d53hx): Refactor: update UpdateCommentUseCase to use ICommentRepository interface.
  bun.lock
  package.json
  project_structure.text
  src/application/dtos/auth.dto.ts
  src/application/services/auth.service.ts
  src/application/use-cases/auth/getSession.useCase.ts
  src/application/use-cases/auth/login.use-case.ts
  src/application/use-cases/auth/refreshToken.useCase.ts
  src/application/use-cases/comment/update-comment.use-case.ts
  src/application/use-cases/index.ts
  src/infrastructure/config/config.ts
  src/presentation/controllers/auth.controller.ts
  src/presentation/middleware/configureMiddlewares.ts
  src/presentation/routes/auth.router.ts
  src/shared/utils/time.utils.ts
Labels: enhancement

#66 ✨:(86a7d5kgh): creation of student login test
  src/tests/integration/logIn/loginStudent.test.ts
Labels: bug, enhancement

#77 ✨ feature (86a7rc0jv): Add support for TUTOR user type; implement…
  bun.lock
  project_structure.text
  src/application/dtos/jobOpportunity.dto.ts
  src/application/dtos/user.dto.ts
  src/application/use-cases/index.ts
  src/application/use-cases/user/add-infomanager-to-university.use-case.ts
  src/application/use-cases/user/add-student-to-tutor.use-case.ts
  src/application/use-cases/user/add-viewer-to-university.use-case.ts
  src/application/use-cases/user/get-infomanagers-by-university.use-case.ts
  src/application/use-cases/user/get-students-by-tutor.use-case.ts
  src/application/use-cases/user/get-viewers-by-university.use-case.ts
  src/domain/entities/user.entity.ts
  src/domain/repositories/user.repository.ts
  src/infrastructure/config/config.ts
  src/infrastructure/database/models/user.model.ts
  src/infrastructure/database/repositories/user.repository.impl.ts
  src/presentation/controllers/user.controller.ts
  src/presentation/routes/user.router.ts
  tsconfig.json
Labels: enhancement, Merge When Approved

#78 ♻️ (86a7qrdvy) (86a7qrkk9) (86a7qrr4g) (86a7qrw8m) (86a7qt0vx) Refactor user management system with role-based user schemas and repositories
  src/application/dtos/user.dto.ts
  src/application/services/auth.service.ts
  src/application/use-cases/user/add-student-to-tutor.use-case.ts
  src/application/use-cases/user/create-user.use-case.ts
  src/domain/entities/user.entity.ts
  src/domain/repositories/user.repository.ts
  src/infrastructure/database/models/admin.model.ts
  src/infrastructure/database/models/index.ts
  src/infrastructure/database/models/infomanager.model.ts
  src/infrastructure/database/models/student.model.ts
  src/infrastructure/database/models/tutor.model.ts
  src/infrastructure/database/models/university.model.ts
  src/infrastructure/database/models/user.base.model.ts
  src/infrastructure/database/models/user.model.ts
  src/infrastructure/database/models/viewer.model.ts
  src/infrastructure/database/repositories/user.repository.impl.ts
  src/presentation/controllers/user.controller.ts
  src/presentation/middleware/jwtMiddleware.ts
  src/tests/integration/logIn/logInViewer.test.ts
  src/tests/integration/logIn/loginStudent.test.ts
Labels: enhancement

#79 ✅ (86a7rekh0), (86a7rear0), (86a7reqcq), (86a7rdq3a) instegration test
  src/presentation/routes/educationalInstitution.router.ts
  src/presentation/routes/major.router.ts
  src/presentation/routes/user.router.ts
  src/tests/integration/crud/infoManagerCrud.test.ts
  src/tests/integration/crud/studentCrud.test.ts
  src/tests/integration/crud/tutorCrud.test.ts
  src/tests/integration/crud/universityCrud.test.ts
Labels: enhancement

#80 ♻️ refactor (86a7w2t44): Replacing cookies with authorization header
  src/application/dtos/auth.dto.ts
  src/application/services/auth.service.ts
  src/presentation/controllers/auth.controller.ts
  src/presentation/routes/major.router.ts
  src/tests/integration/crud/studentCrud.test.ts
Labels: enhancement, Merge When Approved

#76 ✨ Feature (86a7duhea): password retrieval Functionality
  .github/workflows/ci-test.yml
  bun.lock
  package.json
  src/application/use-cases/email/sendRecoveryEmail.useCase.ts
  src/application/use-cases/index.ts
  src/application/use-cases/user/update-user-by-email.use-case.ts
  src/domain/repositories/user.repository.ts
  src/infrastructure/config/config.ts
  src/infrastructure/database/repositories/user.repository.impl.ts
  src/presentation/controllers/email.controller.ts
  src/presentation/controllers/index.ts
  src/presentation/controllers/user.controller.ts
  src/presentation/routes/email.router.ts
  src/presentation/routes/index.ts
  src/presentation/routes/user.router.ts
  src/server.ts
  src/shared/utils/index.ts
  src/shared/utils/url-formatter.ts
Labels: enhancement

#84 ✨ Feature (86a7qfrk0): Crud marketing, support and finances implementation
  src/application/dtos/user.dto.ts
  src/application/use-cases/index.ts
  src/application/use-cases/user/add-finances-to-admin.use-case.ts
  src/application/use-cases/user/add-marketing-to-admin.use-case.ts
  src/application/use-cases/user/add-support-to-admin.use-case.ts
  src/application/use-cases/user/get-finances-by-admin.use-case.ts
  src/application/use-cases/user/get-marketing-by-admin.use-case.ts
  src/application/use-cases/user/get-support-by-admin.use-case.ts
  src/domain/entities/user.entity.ts
  src/domain/repositories/user.repository.ts
  src/infrastructure/database/models/admin.model.ts
  src/infrastructure/database/models/finances.model.ts
  src/infrastructure/database/models/index.ts
  src/infrastructure/database/models/marketing.model.ts
  src/infrastructure/database/models/support.model.ts
  src/infrastructure/database/models/user.base.model.ts
  src/infrastructure/database/repositories/user.repository.impl.ts
  src/presentation/controllers/user.controller.ts
  src/presentation/routes/user.router.ts
Labels: enhancement

#85 ♻️ Refactor: Endpoints in the user router and adding update functionality to all users
  project_structure.text
  src/infrastructure/database/repositories/user.repository.impl.ts
  src/presentation/controllers/user.controller.ts
  src/presentation/routes/user.router.ts
Labels: bug, enhancement, Merge When Approved
