Repository Dataflux-U-nidos/Backend, pull requests merged in 2025-03, with the labels that each got.

#6 86a79qp1a - Config database cluster
  src/infrastructure/config/config.ts
  src/infrastructure/config/index.ts
  src/infrastructure/database/database.ts
  src/infrastructure/database/index.ts
  src/server.ts
  src/shared/utils/index.ts
  src/shared/utils/validateEnv.ts
Labels: enhancement, Merge When Approved

#7 86a77yf32 - Major data contract creation
  bun.lock
  package.json
  src/application/dtos/index.ts
  src/application/dtos/major.dto.ts
  src/application/index.ts
  src/application/use-cases/index.ts
  src/application/use-cases/major/create-major.use-case.ts
  src/application/use-cases/major/delete-major.use-case.ts
  src/application/use-cases/major/get-all-majors.use-case.ts
  src/application/use-cases/major/get-major-by-id.use-case.ts
  src/application/use-cases/major/update-major.use-case.ts
  src/domain/entities/index.ts
  src/domain/entities/major.entity.ts
  src/domain/index.ts
  src/domain/repositories/index.ts
  src/domain/repositories/major.repository.ts
  src/infrastructure/database/index.ts
  src/infrastructure/database/models/index.ts
  src/infrastructure/database/models/major.model.ts
  src/infrastructure/database/repositories/index.ts
  src/infrastructure/database/repositories/major.repository.impl.ts
  src/infrastructure/index.ts
  src/presentation/controllers/index.ts
  src/presentation/controllers/major.controller.ts
  src/presentation/index.ts
  src/presentation/routes/index.ts
  src/presentation/routes/major.router.ts
  src/server.ts
  src/shared/utils/typebox-validator.ts
Labels: enhancement, Merge When Approved

#8 🚑 fix: Importing issues
  src/infrastructure/database/repositories/index.ts
  src/presentation/routes/major.router.ts
Labels: bug

#13 86a77ycub - Institutional Education contract scheme creation
  src/application/dtos/educational_institution.dto.ts
  src/application/dtos/index.ts
  src/application/use-cases/educational-institution/create-educational-institution.use-case.ts
  src/application/use-cases/educational-institution/delete-educational-institution.use-cases.ts
  src/application/use-cases/educational-institution/get-all-educational-institution.use-case.ts
  src/application/use-cases/educational-institution/get-educational-institution-by-id.use-case.ts
  src/application/use-cases/educational-institution/update-educational-institution.use-case.ts
  src/application/use-cases/index.ts
  src/domain/entities/educational-institution.entity.ts
  src/domain/entities/index.ts
  src/domain/repositories/educational-institution.repository.ts
  src/domain/repositories/index.ts
  src/infrastructure/database/models/educational-institution.model.ts
  src/infrastructure/database/models/index.ts
  src/infrastructure/database/repositories/educational-institution.repository.Impl.ts
  src/infrastructure/database/repositories/index.ts
  src/presentation/controllers/educational-institution.controller.ts
  src/presentation/controllers/index.ts
  src/presentation/routes/educational-institution.router.ts
  src/presentation/routes/index.ts
  src/presentation/routes/major.router.ts
  src/server.ts
Labels: enhancement

#25 🐛 error (86a77ycub) corection of import errors and event interface
  src/application/dtos/educational_institution.dto.ts
  src/application/use-cases/educational-institution/create-educational-institution.use-case.ts
  src/application/use-cases/educational-institution/delete-educational-institution.use-cases.ts
  src/application/use-cases/educational-institution/get-all-educational-institution.use-case.ts
  src/application/use-cases/educational-institution/get-educational-institution-by-id.use-case.ts
  src/application/use-cases/educational-institution/update-educational-institution.use-case.ts
  src/domain/entities/educational-institution.entity.ts
  src/domain/repositories/educational-institution.repository.ts
  src/infrastructure/database/models/educational-institution.model.ts
  src/presentation/controllers/educational-institution.controller.ts
  src/presentation/routes/educational-institution.router.ts
Labels: bug, enhancement

#22 ✨ Feature(86a77yd13): Creating user data contract
  src/application/dtos/index.ts
  src/application/dtos/user.dto.ts
  src/application/use-cases/index.ts
  src/application/use-cases/user/create-user.use-case.ts
  src/application/use-cases/user/delete-user.use-case.ts
  src/application/use-cases/user/get-all-users.use-case.ts
  src/application/use-cases/user/get-user-by-id.use-case.ts
  src/application/use-cases/user/update-user.use-case.ts
  src/domain/entities/index.ts
  src/domain/entities/user.entity.ts
  src/domain/repositories/index.ts
  src/domain/repositories/user.repository.ts
  src/infrastructure/database/models/index.ts
  src/infrastructure/database/models/user.model.ts
  src/infrastructure/database/repositories/index.ts
  src/infrastructure/database/repositories/user.repository.impl.ts
  src/presentation/controllers/index.ts
  src/presentation/controllers/user.controller.ts
  src/presentation/routes/index.ts
  src/presentation/routes/major.router.ts
  src/presentation/routes/user.router.ts
  src/server.ts
Labels: enhancement

#27 ✨ (86a77yfk6): creating comment data contract
  src/application/dtos/comment.dto.ts
  src/application/dtos/index.ts
  src/application/use-cases/comment/create-comment.use-case.ts
  src/application/use-cases/comment/delete-comment.use-case.ts
  src/application/use-cases/comment/get-all-comments.use-case.ts
  src/application/use-cases/comment/get-comment-by-id.use-case.ts
  src/application/use-cases/comment/update-comment.use-case.ts
  src/application/use-cases/index.ts
  src/domain/entities/comment.entity.ts
  src/domain/entities/index.ts
  src/domain/repositories/comment.repository.ts
  src/domain/repositories/index.ts
  src/infrastructure/database/models/comment.model.ts
  src/infrastructure/database/models/index.ts
  src/infrastructure/database/repositories/comment.repository.impl.ts
  src/infrastructure/database/repositories/index.ts
  src/presentation/controllers/comment.controller.ts
  src/presentation/controllers/index.ts
  src/presentation/routes/comment.router.ts
  src/presentation/routes/index.ts
  src/server.ts
Labels: enhancement, Merge When Approved

#31 :art: Feature: error handler enhancement and formated code
  src/infrastructure/config/config.ts
  src/presentation/controllers/comment.controller.ts
  src/presentation/controllers/educational-institution.controller.ts
  src/presentation/controllers/jobOpportunity.controller.ts
  src/presentation/controllers/major.controller.ts
  src/presentation/controllers/user.controller.ts
  src/presentation/middleware/configureMiddlewares.ts
  src/presentation/middleware/errorHandler.ts
  src/presentation/middleware/index.ts
  src/server.ts
Labels: enhancement, Merge When Approved

#33 :recycle: Refactor: enum context language to english
  src/application/dtos/educational_institution.dto.ts
  src/application/dtos/major.dto.ts
  src/application/dtos/user.dto.ts
  src/domain/entities/educational-institution.entity.ts
  src/domain/entities/major.entity.ts
  src/domain/entities/user.entity.ts
  src/infrastructure/database/models/educational-institution.model.ts
  src/infrastructure/database/models/major.model.ts
  src/infrastructure/database/models/user.model.ts
Labels: bug

#43 ✏️ Adding timestamp in User and Majors
  eslint.config.js
  package.json
  src/application/dtos/major.dto.ts
  src/application/dtos/user.dto.ts
  src/domain/entities/major.entity.ts
  src/domain/entities/user.entity.ts
  src/infrastructure/database/models/major.model.ts
  src/infrastructure/database/models/user.model.ts
  src/infrastructure/database/repositories/major.repository.impl.ts
  src/infrastructure/database/repositories/user.repository.impl.ts
  src/presentation/controllers/major.controller.ts
  src/presentation/controllers/user.controller.ts
Labels: bug, Merge When Approved

#45 Documentation: agregation of README
  README.md
Labels: documentation

#48 🚑 ✨ creating timestamp data for comment (problems with eslint)
  src/application/dtos/comment.dto.ts
  src/domain/entities/comment.entity.ts
  src/infrastructure/database/models/comment.model.ts
  src/infrastructure/database/repositories/comment.repository.impl.ts
  src/presentation/controllers/comment.controller.ts
Labels: bug, Merge When Approved

#50 ♻️ Refactor: update user-related schemas and repository methods to use UserResponseDto
  src/application/dtos/user.dto.ts
  src/application/use-cases/user/get-all-users.use-case.ts
  src/application/use-cases/user/get-user-by-id.use-case.ts
  src/domain/repositories/user.repository.ts
  src/infrastructure/database/repositories/user.repository.impl.ts
Labels: enhancement, Merge When Approved

#53 ✨ Feature (86a7duut4): implement JWT decoding utility and update middleware to use it
  bun.lock
  package.json
  src/application/dtos/auth.dto.ts
  src/application/services/auth.service.ts
  src/application/use-cases/auth/login.use-case.ts
  src/application/use-cases/index.ts
  src/application/use-cases/user/create-user.use-case.ts
  src/application/use-cases/user/get-user-by-email.use-case.ts
  src/domain/repositories/user.repository.ts
  src/infrastructure/config/config.ts
  src/infrastructure/database/models/comment.model.ts
  src/infrastructure/database/repositories/comment.repository.impl.ts
  src/infrastructure/database/repositories/educationalInstitution.repository.impl.ts
  src/infrastructure/database/repositories/jobOpportunity.repository.impl.ts
  src/infrastructure/database/repositories/major.repository.impl.ts
  src/infrastructure/database/repositories/user.repository.impl.ts
  src/presentation/controllers/auth.controller.ts
  src/presentation/controllers/comment.controller.ts
  src/presentation/controllers/index.ts
  src/presentation/index.ts
  src/presentation/middleware/index.ts
  src/presentation/middleware/jwtMiddleware.ts
  src/presentation/routes/auth.router.ts
  src/presentation/routes/index.ts
  src/presentation/routes/user.router.ts
  src/server.ts
  src/shared/index.ts
  src/shared/utils/index.ts
  src/shared/utils/jwt.utils.ts
Labels: enhancement, Merge When Approved

#52 ♻️ Refactor: update major use cases and repository to use IMajorRepository and MajorResponseDto
  src/application/dtos/major.dto.ts
  src/application/use-cases/major/create-major.use-case.ts
  src/application/use-cases/major/delete-major.use-case.ts
  src/application/use-cases/major/get-all-majors.use-case.ts
  src/application/use-cases/major/get-major-by-id.use-case.ts
  src/application/use-cases/major/update-major.use-case.ts
  src/domain/repositories/major.repository.ts
  src/infrastructure/database/repositories/major.repository.impl.ts
Labels: enhancement, Merge When Approved

#54 (86a7hqqyp) testing branch
  src/server.ts
Labels: documentation, Merge When Approved

#55 ♻️ Refactor (86a7duxx9): add role validation middleware to routes
  src/presentation/routes/comment.router.ts
  src/presentation/routes/educationalInstitution.router.ts
  src/presentation/routes/jobOpportunity.router.ts
  src/presentation/routes/major.router.ts
  src/presentation/routes/user.router.ts
Labels: enhancement, Merge When Approved
