Repository Dataflux-U-nidos/Backend, pull requests merged in 2025-05, with the labels that each got.

#98 ✨ Feature (86a88q99f): Enhance user deletion logic to support cascadi…
  src/application/use-cases/user/delete-user.use-case.ts
  src/presentation/controllers/user.controller.ts
  src/presentation/routes/user.router.ts
Labels: enhancement

#99 ✨ Feature (86a88q91j): Add GetTotalInvestment use case, controller me…
  src/application/dtos/campaign.dto.ts
  src/application/use-cases/campaign/get-total-investment.use-case.ts
  src/application/use-cases/index.ts
  src/domain/repositories/campaign.repository.ts
  src/infrastructure/database/repositories/campaign.repository.impl.ts
  src/presentation/controllers/campaign.controller.ts
  src/presentation/routes/campaign.router.ts
Labels: enhancement

#100 ✨ Feature (86a88q5db) (86a88q8f1) (86a88q8r4): Implement subscription plan management with CRUD operations and routing, total and parcial revenueu
  src/application/dtos/major.dto.ts
  src/application/dtos/subscriptionPlan.dto.ts
  src/application/dtos/user.dto.ts
  src/application/use-cases/index.ts
  src/application/use-cases/major/create-major.use-case.ts
  src/application/use-cases/suscriptionPlan/create-subscription-plan.use-case.ts
  src/application/use-cases/suscriptionPlan/delete-subscription-plan.use-case.ts
  src/application/use-cases/suscriptionPlan/get-all-subscription-plans.use-case.ts
  src/application/use-cases/suscriptionPlan/get-revenue-by-plan.use-case.ts
  src/application/use-cases/suscriptionPlan/get-subscription-plan-by-id.use-case.ts
  src/application/use-cases/suscriptionPlan/get-total-revenue.use-case.ts
  src/application/use-cases/suscriptionPlan/update-subscription-plan.use-case.ts
  src/domain/entities/major.entity.ts
  src/domain/entities/subscriptionPlan.entity.ts
  src/domain/entities/user.entity.ts
  src/domain/repositories/subscriptionPlan.repository.ts
  src/infrastructure/database/models/index.ts
  src/infrastructure/database/models/major.model.ts
  src/infrastructure/database/models/subscriptionPlan.model.ts
  src/infrastructure/database/models/university.model.ts
  src/infrastructure/database/repositories/major.repository.impl.ts
  src/infrastructure/database/repositories/subscriptionPlan.repository.impl.ts
  src/infrastructure/database/repositories/user.repository.impl.ts
  src/presentation/controllers/index.ts
  src/presentation/controllers/major.controller.ts
  src/presentation/controllers/subscriptionPlan.controller.ts
  src/presentation/routes/index.ts
  src/presentation/routes/subscriptionPlan.routes.ts
  src/presentation/routes/user.router.ts
  src/server.ts
Labels: enhancement

#101 ✨ Feature (86a88pz14): Json template for psychometric, vocational and partial tests.
  src/application/use-cases/index.ts
  src/application/use-cases/studentTest/psychometric.use-case.ts
  src/application/use-cases/studentTest/vocational-partial.use-case.ts
  src/application/use-cases/studentTest/vocational.use-case.ts
  src/infrastructure/config/config.ts
  src/presentation/controllers/index.ts
  src/presentation/controllers/studentTest.controller.ts
  src/presentation/routes/index.ts
  src/presentation/routes/studentTest.router.ts
  src/server.ts
Labels: enhancement

#102 🚑 Hotfix: Add special delete route for users with role validation and remove ID-based delete route
  src/presentation/routes/user.router.ts
Labels: bug

#107 ✨ Feature (86a88pbxm): Refactor comment handling to include majorId and userId, update repository methods to return DTOs, and enhance create comment logic with user validation.
  src/application/dtos/comment.dto.ts
  src/application/use-cases/comment/create-comment.use-case.ts
  src/domain/entities/comment.entity.ts
  src/domain/repositories/comment.repository.ts
  src/infrastructure/database/models/comment.model.ts
  src/infrastructure/database/repositories/comment.repository.impl.ts
  src/presentation/controllers/comment.controller.ts
Labels: enhancement

#109 ✅ (86a88xfaj) (86a88xgbf) (86a88xhnw) (86a88xjhx) (86a88xm8w)
  src/tests/integration/businessLogic/majorComments.test.ts
  src/tests/integration/businessLogic/searchEducationalInstitution.test.ts
  src/tests/integration/businessLogic/searchJobOpportunity.test.ts
  src/tests/integration/businessLogic/studentTest.test.ts
  src/tests/integration/crud/financesCrud.test.ts
  src/tests/integration/crud/infoManagerCrud.test.ts
  src/tests/integration/crud/marketingCrud.test.ts
  src/tests/integration/crud/studentCrud.test.ts
  src/tests/integration/crud/supportCrud.test.ts
  src/tests/integration/crud/tutorCrud.test.ts
  src/tests/integration/crud/universityCrud.test.ts
Labels: bug, enhancement

#112 ✨ Feature: Implementing recommendation algorithm
  project_structure.text
  src/application/dtos/jobOpportunity.dto.ts
  src/application/dtos/major.dto.ts
  src/application/dtos/user.dto.ts
  src/application/use-cases/comment/get-comments-by-major.use-case.ts
  src/application/use-cases/index.ts
  src/application/use-cases/major/add-job-opportunity-to-major.use-case.ts
  src/application/use-cases/user/get-recommendations.use-case.ts
  src/application/use-cases/user/update-final-result.use-case.ts
  src/application/use-cases/user/update-test-result.use-case.ts
  src/domain/entities/jobOpportunity.entity.ts
  src/domain/entities/major.entity.ts
  src/domain/entities/user.entity.ts
  src/domain/repositories/comment.repository.ts
  src/domain/repositories/major.repository.ts
  src/domain/repositories/user.repository.ts
  src/infrastructure/database/models/jobOpportunity.model.ts
  src/infrastructure/database/models/major.model.ts
  src/infrastructure/database/models/student.model.ts
  src/infrastructure/database/models/university.model.ts
  src/infrastructure/database/repositories/comment.repository.impl.ts
  src/infrastructure/database/repositories/jobOpportunity.repository.impl.ts
  src/infrastructure/database/repositories/major.repository.impl.ts
  src/infrastructure/database/repositories/user.repository.impl.ts
  src/presentation/controllers/comment.controller.ts
  src/presentation/controllers/major.controller.ts
  src/presentation/controllers/user.controller.ts
  src/presentation/routes/comment.router.ts
  src/presentation/routes/jobOpportunity.router.ts
  src/presentation/routes/major.router.ts
  src/presentation/routes/user.router.ts
  src/tests/integration/businessLogic/majorComments.test.ts
  src/tests/integration/businessLogic/studentTest.test.ts
Labels: enhancement

#113 ♻️ Refactor: Remove EducationalInstitution related code and migrate relevant fields to User entity
  src/application/dtos/educationalInstitution.dto.ts
  src/application/dtos/index.ts
  src/application/dtos/user.dto.ts
  src/application/use-cases/educationalInstitution/createEducationalInstitution.useCase.ts
  src/application/use-cases/educationalInstitution/deleteEducationalInstitution.useCase.ts
  src/application/use-cases/educationalInstitution/getAllEducationalInstitution.useCase.ts
  src/application/use-cases/educationalInstitution/getEducationalInstitutionById.useCase.ts
  src/application/use-cases/educationalInstitution/updateEducationalInstitution.useCase.ts
  src/application/use-cases/index.ts
  src/application/use-cases/user/get-all-users.use-case.ts
  src/domain/entities/educationalInstitution.entity.ts
  src/domain/entities/index.ts
  src/domain/entities/user.entity.ts
  src/domain/repositories/educationalInstitution.repository.ts
  src/domain/repositories/index.ts
  src/domain/repositories/user.repository.ts
  src/infrastructure/database/models/educationalInstitution.model.ts
  src/infrastructure/database/models/index.ts
  src/infrastructure/database/models/student.model.ts
  src/infrastructure/database/models/university.model.ts
  src/infrastructure/database/repositories/educationalInstitution.repository.impl.ts
  src/infrastructure/database/repositories/index.ts
  src/infrastructure/database/repositories/user.repository.impl.ts
  src/presentation/controllers/educationalInstitution.controller.ts
  src/presentation/controllers/index.ts
  src/presentation/controllers/user.controller.ts
  src/presentation/routes/educationalInstitution.router.ts
  src/presentation/routes/index.ts
  src/presentation/routes/user.router.ts
  src/server.ts
Labels: bug

#114 ✨ Feature (86a8gbyn0): Implement getByMajor method in JobOpportunityController to retrieve job opportunities by major
  src/application/use-cases/index.ts
  src/application/use-cases/jobOpportunity/getJobOpportunitiesByMajorUseCase.ts
  src/presentation/controllers/jobOpportunity.controller.ts
  src/presentation/routes/jobOpportunity.router.ts
Labels: enhancement

#116 ✨ Feature (86a8gbz5e) (86a8gbyuz): Add platform statistics functionality with new use case, controller method, route, and DTO
  src/application/dtos/platform-stats.dto.ts
  src/application/dtos/satisfaction-survey.dto.ts
  src/application/use-cases/index.ts
  src/application/use-cases/platformStats/get-platform-stats.use-case.ts
  src/application/use-cases/satisfactionSurvey/create-satisfaction-survey.use-case.ts
  src/application/use-cases/satisfactionSurvey/get-student-surveys.use-case.ts
  src/application/use-cases/satisfactionSurvey/get-survey-stats.use-case.ts
  src/domain/repositories/satisfaction-survey.repository.ts
  src/domain/repositories/user.repository.ts
  src/infrastructure/database/models/satisfaction-survey.model.ts
  src/infrastructure/database/models/student.model.ts
  src/infrastructure/database/repositories/index.ts
  src/infrastructure/database/repositories/satisfaction-survey.repository.impl.ts
  src/infrastructure/database/repositories/user.repository.impl.ts
  src/presentation/controllers/index.ts
  src/presentation/controllers/satisfaction-survey.controller.ts
  src/presentation/controllers/user.controller.ts
  src/presentation/routes/index.ts
  src/presentation/routes/satisfaction-survey.router.ts
  src/presentation/routes/user.router.ts
  src/server.ts
Labels: enhancement

#117 Feature dotnet cuestionary
  src/application/use-cases/email/SendCuestionaryEmailUseCase.ts
  src/application/use-cases/index.ts
  src/application/use-cases/studentTest/cuestionary.use-case.ts
  src/infrastructure/config/config.ts
  src/presentation/controllers/email.controller.ts
  src/presentation/controllers/studentTest.controller.ts
  src/presentation/routes/email.router.ts
  src/presentation/routes/studentTest.router.ts
Labels: enhancement

#119 🐛 Fix Recomendations with university
  src/application/use-cases/index.ts
  src/application/use-cases/user/get-recommendations.use-case.ts
  src/presentation/routes/user.router.ts
Labels: bug, enhancement

#120 ✨ Feature: Add dashboard functionality with routes and controller methods for universities, careers, searched universities, and users
  src/infrastructure/mocks/dashboardData.ts
  src/presentation/controllers/dashboard.controller.ts
  src/presentation/controllers/index.ts
  src/presentation/routes/dashboard.router.ts
  src/presentation/routes/index.ts
  src/server.ts
Labels: enhancement

#121 Fix update
  src/application/use-cases/index.ts
  src/application/use-cases/user/get-recommendations.use-case.ts
  src/presentation/controllers/user.controller.ts
  src/presentation/routes/user.router.ts
Labels: enhancement

#122 ✨ feature: Add functionality to create new job opportunities with an add dialog in AdminManageJobOpScreen (#58)
  src/presentation/routes/jobOpportunity.router.ts
Labels: enhancement
